# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sfApplyPlugin:
    from:
      email: "no-reply@vietlens.com"
      fullname: "The Staff at vietlens.com"
# Please do not touch, this is registration settings (@alexfilatov)
  sfForkedApply:
    applyForm: sfApplyApplyForm
    resetForm: sfApplyResetForm
    resetRequestForm: sfApplyResetRequestForm
    settingsForm: sfApplySettingsForm

    routes:
      apply: /register
      reset: /member/password-reset
      resetRequest: /member/reset-request
      resetCancel: /member/reset-cancel
      validate: /member/confirm/:validate
      settings: /member/settings

    confirmation:
      reset: true
      apply: false
      email: true
      reset_logged: true

  recaptcha:
    enabled:        false
    public_key:     6Ld6MMQSAAAAAIPD9s5RXnI4cgiSc9hfId4jpnxk
    private_key:    6Ld6MMQSAAAAAMxM7AEaXvsr1OfZa5DkbCy08EYg

  rep:
    location_add:        20
    review_add:          10
    review_upvoted:      5
    review_downvoted:    -2
    question_upvoted:    5
    question_downvoted:  -2
    answer_upvoted:      5
    answer_downvoted:    -2
    casting_downvote:    -1

  privilege:
    review_comment_add:  50
    tag_add:             1500
    tag_retag:           500
    casting_helpful:     20
    casting_unhelpful:   140
    casting_flag:        20

  category:
    location: 1
    event: 2
    article: 3
    question: 4

  elastic_realtime:
    location: true
    event: true
    article: true
    question: true
    image: true
    circle: true
    user: true

  paging:
    gallery: 30

  vn_id: 1
  explore_zone_column: 4

  sf_guard_plugin:
    allow_login_with_email: true
    success_signout_url: @homepage

  melody:
    # All Melodies are work with domain name viet-guide.work (dev local domain)
    # In production we need to create twitter/facebook (and register domain in google)
    # apps "vietguide" and assign apps data for corresponding melody

    create_user: true               # to create a user for all melodies

    google:
      key: anonymous
      secret: anonymous
      callback: @connect_google_callback
      api: [contacts]
                                    # needed to create an user based on his email_address
      user:
        first_name:
          call: contacts/me
          path: feed.author.0.name.$t
        username:
          call: contacts/me
          path: feed.id.$t
          prefix: google_
        email_address:
          call: contacts/me
          path: feed.id.$t
          key: true                 # it's a key to retrieve user from other services based on this                                     # if no field is a key all are keys by default.
    facebook:
      id: 146045945467456
      key: b270bf694ca054fb5df26ad1e2834e9d
      secret: 91a10fc91adfa60390f077c7c1c0903d
      callback: @connect_facebook_callback
      scope: [email]                #optionnal - http://developers.facebook.com/docs/authentication/permissions
                                    # needed to create an user based on his email_address
      user:
        username:                   # the name of a field of sfGuardUser
          call: me                  # api call
          path: id                  # path could be user.object.email for example to retrieve the right inforamtion
          prefix: facebook_
        first_name:
          call: me
          path: first_name
        email_address:
          call: me
          path: email
          key: true                 # it's a key to retrieve user from other services based on this information
                                    # if no field is a key all are keys by default.
    twitter:
      key: tNExaGtjqMTBFCMxDCRIw
      secret: zDFRKsYkUlNJ9C4AQLVByeX0K6DQYTQdlnAokSm49Mg
      callback: @connect_twitter_callback
      redirect_register: @connect_twitter_register
      scope: [email]                #optionnal - http://developers.facebook.com/docs/authentication/permissions
                                    # needed to create an user based on his email_address
      user:
        username:                   # the name of a field of sfGuardUser
          call: me
          path: screen_name
          prefix: twitter_
        first_name:
          call: me
          path: name

# Commented because Twitter does not provide email addresses; there are additional case for adding email
#        email_address:
#          call: me
#          path: email
#          key: true
  sfImageTransformPlugin:
    mime_type:
      auto_detect:  true
      library:    gd_mime_type #  gd_mime_type (GD), Fileinfo (PECL), MIME_Type (PEAR)
    font_dir:     %SF_PLUGINS_DIR%/sfImageTransformExtraPlugin/data/example-resources/fonts

  sfLanguageSwitch:
    flagPath:  /sfLanguageSwitchPlugin/images/flag
    availableLanguages:
      en:
        title: english
      vn:
        title: tiếng việt
